blogging/urls.py
from django.urls import path
from blogging.views import BlogListView, BlogDetailView

urlpatterns = [
    path("", BlogListView.as_view(), name="blog_index"),
    path("posts/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from rest_framework import routers
from blogging import views

router = routers.DefaultRouter()
router.register(r"users", views.UserViewSet)
router.register(r"posts", views.PostViewSet)
router.register(r"catagories", views.CatagoryViewSet, "catagory")

urlpatterns = [
    path("", include("blogging.urls")),
    path("api/", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("polling/", include("polling.urls")),
    path("admin/", admin.site.urls),
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
]

polling/urls.py
from django.urls import path
from polling.views import list_view, detail_view

urlpatterns = [
    path("", list_view, name="poll_index"),
    path("polls/<int:poll_id>/", detail_view, name="poll_detail"),
]

blogging/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title


class Catagory(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField(blank=True)
    posts = models.ManyToManyField("Post", blank=True, related_name="categories")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Catagories"

polling/models.py
from django.db import models


class Poll(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.title

blogging/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from rest_framework import viewsets
from rest_framework import permissions
from blogging.models import User, Post, Catagory
from blogging.serializers import UserSerializer, PostSerializer, CatagorySerializer


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint for User
    """

    queryset = User.objects.all().order_by("-date_joined")
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]


class PostViewSet(viewsets.ModelViewSet):
    """
    API endpoint for Post
    """

    queryset = Post.objects.all().order_by("-modified_date")
    serializer_class = PostSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]


class CatagoryViewSet(viewsets.ModelViewSet):
    """
    API endpoint for Catagory
    """

    queryset = Catagory.objects.all()
    serializer_class = CatagorySerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]


class BlogListView(ListView):
    queryset = Post.objects.exclude(published_date__exact=None)
    template_name = "blogging/list.html"


class BlogDetailView(DetailView):
    queryset = Post.objects.exclude(published_date__exact=None)
    template_name = "blogging/detail.html"

polling/views.py
from django.shortcuts import render
from django.http import Http404
from polling.models import Poll


def list_view(request):
    context = {"polls": Poll.objects.all()}
    return render(request, "polling/list.html", context)


def detail_view(request, poll_id):
    try:
        poll = Poll.objects.get(pk=poll_id)
    except Poll.DoesNotExist:
        raise Http404

    if request.method == "POST":
        if request.POST.get("vote") == "Yes":
            poll.score += 1
        else:
            poll.score -= 1
        poll.save()

    context = {"poll": poll}
    return render(request, "polling/detail.html", context)

blogging/templates/blogging/detail.html
{% extends 'base.html' %}

{% block content %}
<a class="backlink" href="/">Home</a>
<h1>{{ object.title }}</h1>
<p class="byline">
	Posted by {{ object.author.username }} &mdash; {{ object.published_date }}
</p>
<div class="post-body">
	{{ object.text }}
</div>
<ul class="categories">
	{% for category in object.categories.all %}
		<li>{{ category }}</li>
	{% endfor %}
</ul>
{% endblock %}

blogging/templates/blogging/list.html
{% extends 'base.html' %}{% block content %}
	<h1>Coolest Posts</h1>
	{% comment %}here is where the query happens{% endcomment %}
	{% for post in post_list %}
	<div class="post">
		<h2>
			<a href="{% url 'blog_detail' post.pk %}">{{ post.title }}</a>
		</h2>
		<p class="byline">
			Posted by {{ post.author.username }} &mdash; {{ post.published_date }}
		</p>
		<div class="post-body">
			{{ post.text }}
		</div>
		<ul class="categories">
			{% for category in post.categories.all %}
				<li>{{ category }}</li>
			{% endfor %}
		</ul>
	</div>
	{% endfor %}
{% endblock %}

mysite/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <title>My Django Blog</title>
	<link type="text/css" rel="stylesheet" href="{% static 'django_blog.css' %}">
  </head>
  <body>
	<div id="header>
		<ul id="control-bar">
			{% if user.is_authenticated %}
				{% if user.is_staff %}
					<li><a href="{% url 'admin:index' %}">admin</a></li>
				{% endif %}
				<li><a href="{% url 'logout' %}">logout</a></li>
			{% else %}
				<li><a href="{% url 'login' %}">login</a></li>
			{% endif %}
		</ul>
	</div>
    <div id="container">
      <div id="content">
      {% block content %}
       [content will go here]
      {% endblock %}
      </div>
    </div>
  </body>
</html>

mysite/templates/login.html
{% extends 'base.html' %}

{% block content %}
<h1>My Blog Login</h1>
<form method='POST'>{% csrf_token %}
	{{ form.as_p }}
	<p><input type="submit" value="Log In"></p>
</form>
{% endblock %}

polling/templates/polling/detail.html
{% extends "base.html" %}
{% block content %}
<h1>{{ poll.title }}</h1>
<div class="poll-body">
    {{ poll.text }}
</div>
<div class="poll-score">
    Current score: {{ poll.score }} <br/>
	or is it {{ score }}
</div>
<div class="poll-vote">
    <form method="POST">
        {% csrf_token %}
        <input type="submit" name="vote" value="Yes">
        <input type="submit" name="vote" value="No">
    </form>
</div>
{% endblock %}

polling/templates/polling/list.html
{% extends "base.html" %}
{% block content %}
<h1>Polls</h1>
{% for poll in polls %}
    <div class="poll">
        <h2>
            <a href="{% url 'poll_detail' poll.pk %}">{{ poll.title }}</a>
        </h2>
    </div>
{% endfor %}
{% endblock %}